parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    # Paramètres d'email
    app.email.from: 'noreply@livridea.fr'
    app.email.contact: 'contact@livridea.fr'
    app.email.admin: 'admin@livridea.fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $targetDirectory: '%uploads_directory%'
    App\Service\LinkGenerator:
        public: true
    App\Service\FileUploader: ~

    Detection\MobileDetect:
        class: Detection\MobileDetect

    App\Service\DeviceDetectorService:
        arguments:
            $mobileDetect: '@Detection\MobileDetect'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
